### ISSUE TITLE
PLEASE MARK AS SOLVED i keep getting a Failed to change username: error

### ISSUE THREAD

**Issue by nono2poor** [0xf15/change-username-tiktok#15]
i keep getting a Failed to change username: error

**Comment by Ndgjdg692716940h** [comment]
### ابي اغير اسم المستخدم تيك توك

**Comment by Ndgjdg692716940h** [comment]
ابي اغير الاسم المستخدم تيك توك

**Comment by nono2poor** [comment]
i was just having internet issues nvm me

**Comment by nono2poor** [comment]
i was just using a broken unicode char nvm me
