### ISSUE TITLE
{"log_pb":{"impr_id":"20240807171238A7770F96DC2BB41DE1C9"},"status_code":8,"status_msg":"Login expired"}

### ISSUE THREAD

**Issue by kqdz** [0xf15/change-username-tiktok#3]
{"log_pb":{"impr_id":"20240807171238A7770F96DC2BB41DE1C9"},"status_code":8,"status_msg":"Login expired"}

**Comment by 0xf15** [comment]
fixed

**Comment by Amoduuu** [comment]
Failed to change username: {"log_pb":{"impr_id":"20240902092700B1EFB45C3687E36C77C3"},"status_code":3002284,"status_msg":"Slow down, you are editing too fast."}
Більше хаків тут: t.me/cybersociety ( help me plz )
