### ISSUE TITLE
Traceback (most recent call last):   File "c:\Users\Dmitryi365\Desktop\x.py", line 183, in <module>     import requests ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by dmitryi365** [0xf15/change-username-tiktok#39]
Traceback (most recent call last):
  File "c:\Users\Dmitryi365\Desktop\x.py", line 183, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by Merkintaaa-svg** [comment]
pip install requests

**Comment by Denisboi** [comment]
бро закрывай issue, это фиксится просто той командой, что тот чел скинул

**Comment by akquenti** [comment]
налетели с тиктока, модуль установить проблема

**Comment by andrewzaycew** [comment]
Tiktok момент
