### ISSUE TITLE
{"log_pb":{"impr_id":"20240813123146350DDCEB80528600327C"},"status_code":3002284,"status_msg":"Slow down, you are editing too fast."}

### ISSUE THREAD

**Issue by andrewzaycew** [0xf15/change-username-tiktok#43]
Failed to change username: {"log_pb":{"impr_id":"20240813123146350DDCEB80528600327C"},"status_code":3002284,"status_msg":"Slow down, you are editing too fast."}
telegram @harbi

[Program finished]

**Comment by superisuer** [comment]
Tiktok fixed this bug

**Comment by andrewzaycew** [comment]
> Tiktok fixed this bug

bad, but let's think that it is not so, we need to make money 🤑🤑🤑🤑

**Comment by superisuer** [comment]
> > Tiktok fixed this bug
> 
> bad, but let's think that it is not so, we need to make money 🤑🤑🤑🤑

 думаешь выйдет фикс?

**Comment by andrewzaycew** [comment]
> > > Tiktok fixed this bug
> > 
> > 
> > bad, but let's think that it is not so, we need to make money 🤑🤑🤑🤑
> 
> думаешь выйдет фикс?

Надеюсь

**Comment by superisuer** [comment]
> > > > Tiktok fixed this bug
> > > 
> > > 
> > > bad, but let's think that it is not so, we need to make money 🤑🤑🤑🤑
> > 
> > 
> > думаешь выйдет фикс?
> 
> Надеюсь

ФИКСАНУЛИ
